# Generated by Django 5.1.3 on 2024-11-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0002_customuser_is_occupant_customuser_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_chosen_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
