# Generated by Django 5.1.3 on 2024-11-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0003_customuser_has_chosen_role_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_chosen_role',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('occupant', 'Occupant')], max_length=10, null=True),
        ),
    ]
