# Generated by Django 5.1.3 on 2024-11-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0004_remove_customuser_has_chosen_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_chosen_initial_role',
            field=models.BooleanField(default=False),
        ),
    ]
