# Generated by Django 5.1.3 on 2024-11-12 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region_registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('OFFICE', 'Office Building'), ('APARTMENT', 'Rental Apartment'), ('CHURCH', 'Church'), ('SCHOOL', 'School'), ('HOME', 'Personal Home'), ('BUSINESS', 'Business'), ('OTHER', 'Other')], max_length=20)),
                ('plus_code', models.CharField(max_length=20, unique=True)),
                ('size', models.IntegerField(help_text='Number of buildings, units, or rooms')),
                ('is_story_building', models.BooleanField(default=False)),
                ('number_of_stories', models.IntegerField(blank=True, null=True)),
                ('establishment_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region_registration.region')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'owner', 'region'), name='unique_establishment_per_owner_region')],
            },
        ),
    ]
